fix(styles): Don't clip radio buttons
bpmn-io/form-js pull request #1261
Opened 2024-09-11 15:23 UTC by vsgoulart

Related to https://github.com/bpmn-io/form-js/pull/1140

Closes https://github.com/camunda/camunda/issues/19945

- [ ] This PR adds a new `form-js` element or visually changes an existing component.
  - => In that case, we need to ensure we follow up on this, e.g. by [creating an issue in Tasklist](https://github.com/camunda/tasklist/issues/new/choose)

2024-09-11 18:56 UTC, Skaiir requested changes
The clipping is intentional for long labels. With this change you can totally break the structure unfortunately. And since it can be driven by variables we don't really want that. I'm not sure if it's possible to properly do clipping but also have the label wrap the checkbox in the DOM. 

I think we need to split them, just generally, even if it means adding a nesting node to flexbox them.

2024-09-12 11:10 UTC, vsgoulart reviewed
@Skaiir There are some problems with the Carbonization, there's no padding between radio items and the checked state is not working on checkboxes or radio buttons anymore
![Uploading Screenshot 2024-09-12 at 14.06.16.png…]()

2024-09-12 11:10 UTC, vsgoulart commented on packages/form-js-viewer/src/render/components/form-fields/Checklist.js
> +            <div className="fjs-inline-label" key={index}>
Do not use indexes as keys, it can cause problems.
Let's use some variation of the `domId`

2024-09-12 11:10 UTC, vsgoulart commented on packages/form-js-viewer/src/render/components/form-fields/Checklist.js
> +                label={o.label}
Let's use the opportunity to improve this code and renamed the variable to not use a single character name, let's use `option` instead of `o`

2024-09-12 11:10 UTC, vsgoulart commented on packages/form-js-viewer/src/render/components/form-fields/Radio.js
> +            <div className="fjs-inline-label" key={index}>
Let's improve the key here too

2024-09-13 09:02 UTC, merged