Allow to set custom properties
bpmn-io/form-js pull request #226
Opened 2022-02-16 16:41 UTC by smbea

Closes #199

2022-02-16 20:31 UTC, MaxTru requested changes
Quick smoke test: I get an error in the console when adding multiple values =>
![Peek 2022-02-16 21-30](https://user-images.githubusercontent.com/42800119/154351935-7028132b-b0c8-496d-b334-2faf16383e67.gif)

2022-02-16 20:33 UTC, MaxTru commented on packages/form-js-editor/src/render/components/properties-panel/groups/CustomValuesGroup.js
> +    <Group label="Custom Properties" addEntry={ addEntry } hasEntries={ hasEntries }>
Let's use sentence case in the label. So `Custom properties`.

2022-02-17 08:25 UTC, smbea commented
> Quick smoke test: I get an error in the console when adding multiple values 

This is also the case for the radio and select values. I will try to figure out why this happens

2022-02-17 08:26 UTC, MaxTru commented
> > Quick smoke test: I get an error in the console when adding multiple values
> 
> This is also the case for the radio and select values. I will try to figure out why this happens

Ah I see - thanks for the note. Then maybe seperate issue.

2022-02-17 08:46 UTC, smbea commented
> Ah I see - thanks for the note. Then maybe seperate issue.

I gave it a quick look but couldn't fix it easily, so maybe I can create a  separate issue for this

2022-02-17 08:57 UTC, philippfromme commented
> I gave it a quick look but couldn't fix it easily, so maybe I can create a separate issue for this

Let me have a look. Maybe it's an easy fix.

2022-02-17 09:04 UTC, smbea commented
I believe this was fixed for the `custom properties` with my new push. I had a typo there which caused the error for `custom properties`.

But I didn't touch the `values` for select and radio - these are still causing the error. I think this isn't a problem for `custom properties` because of the key attribute being unique, unlike in `values`.

2022-02-17 09:16 UTC, philippfromme commented
The issue is unrelated. It's about Preact keys. I'll look into it. It doesn't block this pull request.

2022-02-17 11:05 UTC, philippfromme approved these changes
I've added a couple of adjustments.

One thing we have to be careful about is mutating data that should not be mutated outside of command execution:

```javascript
const removeEntry = () => {
  delete properties[key]; // ⚠️⚠️⚠️
  editField(field, [ 'properties' ], properties);
};
```

cf. https://github.com/bpmn-io/form-js/pull/226/commits/ea06435016cd01a126b0f8366e393a13a93f43e7#diff-d9aa085d1d1aa4b6c29d41a645a753822e359cb36ac6d33ce0a7a6ffd138b3dbR51

cf. https://github.com/bpmn-io/form-js/pull/226/commits/ea06435016cd01a126b0f8366e393a13a93f43e7#diff-797efb599d143b3baeb4b8bdfd2c2c603de68ce1c64b55af7a6dbd4a561f610bR18

Furthermore, since we added a new property `properties` to the schema we need to bump the schema version as it's the convention for form-js (we don't use JSON schema).

cf. https://github.com/bpmn-io/form-js/pull/226/commits/560220c308e450b9bd42bfc7b667df7eae7ad0de

As for code style, we generally don't omit curly braces as it's error-prone:

```javascript
if (properties[value])
  return 'Must be unique.'; // ⚠️⚠️⚠️
```

cf. https://github.com/bpmn-io/form-js/pull/226/commits/ca6efe3f037817b8a4d128dff49cb69fa9254dac#diff-d9aa085d1d1aa4b6c29d41a645a753822e359cb36ac6d33ce0a7a6ffd138b3dbL39

Good job! 👏🏻

2022-02-17 11:09 UTC, philippfromme commented
Maybe you can follow up with https://github.com/bpmn-io/form-js/issues/227.

2022-02-17 11:11 UTC, smbea commented
@philippfromme thanks for the info! I'm working on something else at the moment, but I'll add that one to my radar for when I have time

2022-02-17 12:33 UTC, MaxTru approved these changes

2022-02-17 12:35 UTC, merged