chore(viewer): add h6 to the available HTML tags
bpmn-io/form-js pull request #450
Opened 2022-12-02 17:47 UTC by adrianmarinwork

Closes #412

2022-12-04 12:23 UTC, pinussilvestrus approved these changes
Looks good to me! Thank you very much 🎉

2022-12-04 12:29 UTC, pinussilvestrus requested changes
I was a bit too fast and didn't wait for the CI 😅 Let's fix the test and merge afterward!

2022-12-04 12:29 UTC, pinussilvestrus commented on packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js
> +###### h6
We need to adjust the `expect` part of this test as well: https://github.com/bpmn-io/form-js/pull/450/files#diff-f782522d93784395284f1b8e2c8b29c8ff07908fcb77815c9f527d9aa8222e0dR83

You can execute the tests locally as well via `npm run test` or `npm run dev -- '@bpmn-io/form-js-viewer`

2022-12-04 13:28 UTC, adrianmarinwork commented
Okay, I've updated the expected value of the test with the new HTML tags!

2022-12-05 07:52 UTC, merged

2022-12-05 07:52 UTC, pinussilvestrus commented
Works now, thanks! 👍