Scalable component library
bpmn-io/form-js pull request #505
Opened 2023-01-20 10:28 UTC by pinussilvestrus

Closes #503 
Related to https://github.com/camunda/form-playground/pull/50

2023-01-23 07:48 UTC, pinussilvestrus commented
To be considered: updating the dragging state

![image](https://user-images.githubusercontent.com/9433996/213988881-2411e831-51b5-4b66-8f93-8cfb988d1b64.png)

2023-01-23 10:06 UTC, vsgoulart reviewed
Looks good! Just some small comments

2023-01-23 10:06 UTC, vsgoulart approved these changes

2023-01-23 10:17 UTC, pinussilvestrus commented on packages/form-js-editor/assets/form-js-editor.css
> +  --color-palette-text: var(--color-grey-225-10-15);
:+1: Let's have an issue to start a conversation. I think we can learn a lot from Carbon here in terms of customization!

2023-01-23 15:06 UTC, vsgoulart commented on packages/form-js-editor/assets/form-js-editor.css
> +  --color-palette-text: var(--color-grey-225-10-15);
Done #515

2023-01-27 14:06 UTC, pinussilvestrus commented
@RomanKostka I updated the drag preview as you proposed. I like 👍 

![Kapture 2023-01-27 at 15 06 11](https://user-images.githubusercontent.com/9433996/215106153-2fa6463c-cf72-4231-9e52-365cd7204411.gif)

2023-01-27 14:07 UTC, pinussilvestrus commented
Let me know when there is something else. I would merge it otherwise 👍

2023-01-27 17:47 UTC, christian-konrad commented
A quick thing: we should add `user-select: none`, while dragging, I accidently selected all the labels:
<img width="245" alt="Bildschirmfoto 2023-01-27 um 18 44 15" src="https://user-images.githubusercontent.com/56470362/215157259-fb84749d-3445-487e-90fa-c64be66dd6a9.png">

2023-01-27 18:05 UTC, christian-konrad requested changes
Unfortunately, it is now cropping the palette already under 1500px:

<img width="1655" alt="Bildschirmfoto 2023-01-27 um 19 05 06" src="https://user-images.githubusercontent.com/56470362/215161475-f7f5557f-9e05-4e52-a385-8d0a31ba5d82.png">

2023-01-30 06:24 UTC, Skaiir commented
> @RomanKostka I updated the drag preview as you proposed. I like 👍

Now onto dynamically calculating the angle of the transform based on the acceleration of the cursor :trollface:

2023-01-30 10:18 UTC, pinussilvestrus commented
> Unfortunately, it is now cropping the palette already under 1500px:

I will adjust this via https://github.com/camunda/form-playground/pull/50

2023-01-31 10:19 UTC, pinussilvestrus commented
@RomanKostka @christian-konrad, the PR should be ready now. Let me know if there is anything left or whether we can merge it 👍

2023-02-01 07:47 UTC, christian-konrad approved these changes
lgtm

2023-02-01 15:31 UTC, merged

2023-02-01 15:31 UTC, pinussilvestrus commented
Merged it now, as something's going on with CodeCov (unrelated to this PR)

🎉