Fixed transparent input backgrounds and disabled state borders
bpmn-io/form-js pull request #570
Opened 2023-03-21 15:33 UTC by Skaiir

Closes #568

![image](https://user-images.githubusercontent.com/17801113/226657093-6ecf4efd-8d0f-4959-a8b1-b4f2b61ba2bd.png)

2023-03-21 15:36 UTC, vsgoulart requested changes

2023-03-21 15:41 UTC, Skaiir commented on packages/form-js-viewer/src/render/components/form-fields/Number.js
> -        <div class={ classNames('fjs-number-arrow-container', { 'fjs-disabled': disabled }) }>
I did not, fair enough, won't touch them then.

2023-03-21 15:43 UTC, pinussilvestrus commented
If we merge this to `master` (which makes sense), I'm wondering whether auto-merge to `develop` will work here as we are touching files that do not exist on `develop` anymore (they were renamed to `*-base.css`) 🤔

2023-03-21 15:46 UTC, Skaiir commented
@pinussilvestrus I guess it won't, but then we have to manually do it instead I guess? Or I can hold off on merging this one entirely.

2023-03-22 08:49 UTC, vsgoulart requested changes
![image](https://user-images.githubusercontent.com/1022916/226849336-5ad873cf-faef-497b-abb5-e5f3f106226d.png)
It's still broken to me. Is the deployment up to date?

2023-03-22 09:11 UTC, Skaiir commented
@vsgoulart It should be, but maybe there's some issues with stylesheets? Not sure why the changes aren't on there, could you try locally?

2023-03-22 09:38 UTC, vsgoulart approved these changes

2023-03-22 09:39 UTC, merged

2023-03-22 15:01 UTC, pinussilvestrus commented
> @vsgoulart ~It should be, but maybe there's some issues with stylesheets? Not sure why the changes aren't on there, could you try locally?~
> 
> Nevermind new deployment got you covered, took a bit to update the cache.

Yeah it can took a while until the update is done, unfortunately Netlify build hooks are async.